### ISSUE TITLE
ERROR com.googlesource.gerrit.plugins.replication.ReplicationQueue

### ISSUE THREAD

**Issue by unaheidi** [GerritCodeReview/plugins_replication#1]
**We use replication v2.9-rc2 plugin between server-A(gerrit v2.9-rc2) and server-B(gerrit v2.9-rc2). After creating a new change with commit(83c40032b8a066b6195ca4bfe10a63f3ea4ed914) , the error.log on server-A reported the following error:**
[2016-07-15 20:29:15,682] ERROR com.googlesource.gerrit.plugins.replication.ReplicationQueue : Cannot replicate to ssh://name@server-B:29418/scm/AAA.git
org.eclipse.jgit.errors.TransportException: ssh://name@server-B:29418/scm/AAA.git: error occurred during unpacking on the remote end: error Missing unknown 83c40032b8a066b6195ca4bfe10a63f3ea4ed914
    at org.eclipse.jgit.transport.BasePackPushConnection.readStatusReport(BasePackPushConnection.java:319)
    at org.eclipse.jgit.transport.BasePackPushConnection.doPush(BasePackPushConnection.java:200)
    at org.eclipse.jgit.transport.BasePackPushConnection.push(BasePackPushConnection.java:152)
    at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:165)
    at org.eclipse.jgit.transport.Transport.push(Transport.java:1173)
    at org.eclipse.jgit.transport.Transport.push(Transport.java:1219)
    at com.googlesource.gerrit.plugins.replication.PushOne.pushVia(PushOne.java:394)
    at com.googlesource.gerrit.plugins.replication.PushOne.runImpl(PushOne.java:366)
    at com.googlesource.gerrit.plugins.replication.PushOne.runPushOperation(PushOne.java:271)
    at com.googlesource.gerrit.plugins.replication.PushOne.access$000(PushOne.java:78)
    at com.googlesource.gerrit.plugins.replication.PushOne$1.call(PushOne.java:244)
    at com.googlesource.gerrit.plugins.replication.PushOne$1.call(PushOne.java:241)
    at com.google.gerrit.server.util.RequestScopePropagator$5.call(RequestScopePropagator.java:222)
    at com.google.gerrit.server.util.RequestScopePropagator$4.call(RequestScopePropagator.java:201)
    at com.google.gerrit.server.git.PerThreadRequestScope$Propagator$1.call(PerThreadRequestScope.java:75)
    at com.googlesource.gerrit.plugins.replication.PushOne.run(PushOne.java:241)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:364)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744) 

**The above error means the replication failed. How to resolve it ?**

**Comment by lucamilanesio** [comment]
This is only a mirror repo, can you please post the message to the Gerrit mailing list?

**Comment by unaheidi** [comment]
Thanks a lot.
